### ISSUE TITLE
How to update a value?

### ISSUE THREAD

**Issue by risharde** [nodeGame/NDDB#14]
Hi, I need some help since the documentation doesn't seem to mention this. How does one edit/update a value with the database?
Super confused and currently super critical for me to continue working with this library, please let me know, thanks!

I've tried intelisense but there's no suggestion in VSCODE, tried to look at the source code as well but couldn't search to find an update function.

**Comment by risharde** [comment]
Think I found the function NDDB.prototype.insert
I still am trying to understand how to use it

**Comment by shakty** [comment]
Hi,

Welcome to this forum!

node.game.memory is an instance of NDDB: https://github.com/nodeGame/NDDB

If you want to update an item, you need to select it in some way:
https://github.com/nodeGame/nodegame/wiki/Memory-Database-Select-Queries-v7

and simply edit it. The updated value is reflected in the database.

Let me know if you have any other questions. Cheers,
Stefano

Am Sa., 30. Apr. 2022 um 18:39 Uhr schrieb risharde <
***@***.***>:

**Comment by risharde** [comment]
@shakty thanks for the welcome and good to be here, thanks also for the response, this is exactly what I needed! I didn't realize that you had documentation under the wiki section, I wonder if I missed that from the readme. If it's not linked in the readme, definitely consider adding it! 

Thanks again, this is great!!
